name = "vite-react-static-assets" # Changed name
compatibility_date = "2024-07-16" # Retain the previous compatibility date

# Configure for deploying a directory of static assets with a Worker
[assets]
directory = "./dist"
