name = "vite-react-typescript-starter"
compatibility_date = "2024-07-16"

# Configure for deploying a static site (Cloudflare Pages)
[pages]
# The directory containing your static assets.
# It should be the output directory of your build command.
assets.directory = "./dist"

# Optional: Configure a custom build command if needed
# pages_build_output_dir = "./dist"

# Optional: Include or exclude files from the deployment
# assets.include = ["*.html", "*.css", "*.js"]
# assets.exclude = ["node_modules/*"]