name = "vite-react-typescript-starter"
compatibility_date = "2024-07-16" # Retain the previous compatibility date

# Configure for deploying a directory of static assets with a Worker
# This is used when the platform executes 'wrangler versions upload' or 'wrangler deploy'
# and expects a Worker configuration.
[assets]
directory = "./dist"

# If a main worker script (e.g., src/index.ts) were present and needed, it would be:
# main = "src/index.ts"
# However, we are deploying only static assets, so 'main' is omitted.
# Wrangler should serve from the 'assets.directory' if 'main' is not specified.
